### ISSUE TITLE
A /testvote command (not an issue, a suggestion)

### ISSUE THREAD

**Issue by monatizd** [Pixelmon-Development/SimpleVoteRewards#2]
It would be good to have a /testvote command inside the plugin to let us test our configs and to see if they work, like SeriousVote has

**Comment by danorris709** [comment]
I can add this but in case you don't already know. There's a fakevote command with NuVotifier (/fakevote) to test the voting services

**Comment by danorris709** [comment]
Implemented in #3. Adding a release now
